# Generated by Django 4.0.6 on 2022-07-26 07:11

from django.db import migrations
from django.contrib.auth.models import User
from website.models import Profile


def create_profile_for_previous_users(apps, schema_editor):
    """
    Create profiles for users generated before Profile class was implemented
    """
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile_for_previous_users)
    ]
