# Generated by Django 4.0.6 on 2022-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
        migrations.AddField(
            model_name='pin',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved', to='website.profile'),
        ),
    ]
