# Generated by Django 4.0.6 on 2022-07-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
