# Generated by Django 4.0.6 on 2022-08-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_pin_likes_pin_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
