# Generated by Django 4.0.6 on 2022-08-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_pin_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='website.profile'),
        ),
    ]
